### PR TITLE
Minor fix in README

### PR DESCRIPTION
**Pull request by orium**

### CODE REVIEW

**Comment by phaazon** [comment]
The feature seems to be in an inconsistent shape, since trying to link to `std::vec::Vec` for instance doesn’t find the symbol. I’ll make the change since your PR doesn’t pass CI.

**Comment by orium** [comment]
> The feature seems to be in an inconsistent shape, since trying to link to std::vec::Vec for instance doesn’t find the symbol.

I've never implemented support to refer to a standard library like `std::vec::Vec`, you have to use an absolute name: `::std::vec::Vec`.  What I implemented was an MVP.  To have support for `std::vec::Vec` things get significantly more complicated: you have to implement logic to check if `std::foo` refers to the standard library or to a relative symbol in your crate: `crate::std::foo` (this applies to `std` as well as other standard library crates like `alloc`, `core`, etc). 

>> I’ll make the change since your PR doesn’t pass CI.

It doesn't pass CI because I updated the README and forgot to update the rustdoc in `lib.rs`.

**Comment by phaazon** [comment]
My point was that `::std::vec::Vec` doesn’t work.

**Comment by orium** [comment]
oh, that's weird to me.  Debugging it...

**Comment by orium** [comment]
Yeah, the reason is that `Vec` is defined in the `alloc::vec` module and then re-exported in `std`.  We don't follow re-exports.  That's a shame since this pattern is common in the standard library.  I think this should be doable.  I'll try to work on this.

**Pull request closed without merging**
